server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/view/
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: account
    password: account
  jpa:
    show-sql: true